export const contractABI = [
  {
    inputs: [
      { internalType: "int256", name: "_priceForOneCredit", type: "int256" },
      { internalType: "int256", name: "_priceForThreeCredits", type: "int256" },
      { internalType: "int256", name: "_priceForFiveCredits", type: "int256" },
    ],
    name: "artistSetPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "artists",
    outputs: [
      { internalType: "string", name: "name", type: "string" },
      { internalType: "int256", name: "priceForOneCredit", type: "int256" },
      { internalType: "int256", name: "priceForThreeCredits", type: "int256" },
      { internalType: "int256", name: "priceForFiveCredits", type: "int256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_artist", type: "address" },
      { internalType: "uint256", name: "_creditAmount", type: "uint256" },
      { internalType: "string", name: "_creditType", type: "string" },
    ],
    name: "buyCredit",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_p2rRecordUID", type: "uint256" },
      {
        internalType: "uint256",
        name: "_totalNumberOfClaims",
        type: "uint256",
      },
    ],
    name: "claimRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_artist", type: "address" }],
    name: "getCreditRemainings",
    outputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getLatestP2RID",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "numberOfP2RRecords",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "p2rRecords",
    outputs: [
      { internalType: "address", name: "artist", type: "address" },
      { internalType: "address", name: "fan", type: "address" },
      { internalType: "uint256", name: "totalAmountPaid", type: "uint256" },
      { internalType: "uint256", name: "credit", type: "uint256" },
      { internalType: "string", name: "creditType", type: "string" },
      { internalType: "uint256", name: "creditCompleted", type: "uint256" },
      { internalType: "uint256", name: "timestamp", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_p2rRecordUID", type: "uint256" },
      {
        internalType: "uint256",
        name: "_totalNumberOfRefunds",
        type: "uint256",
      },
    ],
    name: "refundCredits",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_name", type: "string" },
      { internalType: "int256", name: "_priceForOneCredit", type: "int256" },
      { internalType: "int256", name: "_priceForThreeCredits", type: "int256" },
      { internalType: "int256", name: "_priceForFiveCredits", type: "int256" },
    ],
    name: "registerNewArtist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
